import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const webhookEvents = sqliteTable("webhook_events", {
  eventId: text("event_id").primaryKey(),
  source: text("source").notNull(),
  eventType: text("event_type").notNull(),
  routeId: text("route_id"),
  flowId: text("flow_id"),
  ownerAgent: text("owner_agent"),
  status: text("status").notNull(),
  payloadPath: text("payload_path"),
  correlationId: text("correlation_id"),
  lastError: text("last_error"),
  attemptCount: integer("attempt_count").notNull().default(0),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});

export const taskSnapshots = sqliteTable("task_snapshots", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  board: text("board").notNull(),
  status: text("status").notNull(),
  owner: text("owner").notNull(),
  assigneeType: text("assignee_type").notNull(),
  assignee: text("assignee"),
  agentStatus: text("agent_status").notNull(),
  createdOn: text("created_on").notNull(),
  remindOn: text("remind_on").notNull(),
  runId: text("run_id").notNull(),
  flowId: text("flow_id"),
  detailsRef: text("details_ref").notNull(),
  resultsRef: text("results_ref").notNull(),
  logRef: text("log_ref").notNull(),
  checked: integer("checked", { mode: "boolean" }).notNull().default(false),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});

export const runtimeTasks = sqliteTable("runtime_tasks", {
  taskId: text("task_id").primaryKey(),
  runtime: text("runtime"),
  status: text("status").notNull(),
  agentId: text("agent_id"),
  label: text("label"),
  ownerKey: text("owner_key"),
  sourceId: text("source_id"),
  runId: text("run_id"),
  deliveryStatus: text("delivery_status"),
  terminalSummary: text("terminal_summary"),
  createdAt: integer("created_at"),
  startedAt: integer("started_at"),
  endedAt: integer("ended_at"),
  lastEventAt: integer("last_event_at"),
  cleanupAfter: integer("cleanup_after"),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});

export const taskFlows = sqliteTable("task_flows", {
  flowId: text("flow_id").primaryKey(),
  ownerKey: text("owner_key"),
  goal: text("goal"),
  status: text("status").notNull(),
  currentStep: text("current_step"),
  blockedTaskId: text("blocked_task_id"),
  blockedSummary: text("blocked_summary"),
  createdAt: integer("created_at"),
  startedAt: integer("started_at"),
  endedAt: integer("ended_at"),
  lastEventAt: integer("last_event_at"),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});

export const auditFindings = sqliteTable("audit_findings", {
  findingId: text("finding_id").primaryKey(),
  kind: text("kind").notNull(),
  severity: text("severity").notNull(),
  code: text("code").notNull(),
  status: text("status"),
  token: text("token"),
  detail: text("detail").notNull(),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});

export const memoryHealth = sqliteTable("memory_health", {
  workspaceId: text("workspace_id").primaryKey(),
  workspacePath: text("workspace_path").notNull(),
  hasAgentsMd: integer("has_agents_md", { mode: "boolean" }).notNull().default(false),
  hasMemoryMd: integer("has_memory_md", { mode: "boolean" }).notNull().default(false),
  memoryDirPresent: integer("memory_dir_present", { mode: "boolean" }).notNull().default(false),
  hasTodayDaily: integer("has_today_daily", { mode: "boolean" }).notNull().default(false),
  latestDaily: text("latest_daily"),
  qmdHealthy: integer("qmd_healthy", { mode: "boolean" }).notNull().default(false),
  qmdMessage: text("qmd_message").notNull(),
  status: text("status").notNull(),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});

export const cronJobs = sqliteTable("cron_jobs", {
  jobId: text("job_id").primaryKey(),
  name: text("name").notNull(),
  agentId: text("agent_id").notNull(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  scheduleKind: text("schedule_kind").notNull(),
  scheduleLabel: text("schedule_label").notNull(),
  sessionTarget: text("session_target"),
  wakeMode: text("wake_mode"),
  lastRunStatus: text("last_run_status"),
  lastRunAtMs: integer("last_run_at_ms"),
  nextRunAtMs: integer("next_run_at_ms"),
  lastDurationMs: integer("last_duration_ms"),
  deliveryMode: text("delivery_mode"),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});

export const cronRuns = sqliteTable("cron_runs", {
  runId: text("run_id").primaryKey(),
  jobId: text("job_id").notNull(),
  ts: integer("ts").notNull(),
  action: text("action").notNull(),
  status: text("status").notNull(),
  summary: text("summary"),
  delivered: integer("delivered", { mode: "boolean" }),
  deliveryStatus: text("delivery_status"),
  sessionId: text("session_id"),
  sessionKey: text("session_key"),
  runAtMs: integer("run_at_ms"),
  durationMs: integer("duration_ms"),
  nextRunAtMs: integer("next_run_at_ms"),
  model: text("model"),
  provider: text("provider"),
  recordedAt: text("recorded_at").notNull(),
  rawJson: text("raw_json").notNull(),
});
